[server]
hostname = "wso-mi"
hot_deployment = true 

[user_store]
type = "read_only_ldap"

[keystore.primary]
file_name="wso2carbon.jks"
type="JKS"
password="wso2carbon"
alias="wso2carbon"
key_password="wso2carbon"

[keystore.internal]
file_name="wso2carbon.jks"
type="JKS"
password="wso2carbon"
alias="wso2carbon"
key_password="wso2carbon"

[truststore]
file_name="client-truststore.jks"
type="JKS"
password="wso2carbon"
alias="symmetric.key.value"
algorithm="AES"