server:
  port : 4285
  error:
    whitelabel:
      # Disble the default error page displayed in browsers in case of a server error
      enabled: false

sgi:
  time-zone: "Europe/Madrid"

spring:
  profiles:
    # Set spring-profile using maven
    include: @spring.profiles.active@
  jpa:
    properties:
      hibernate:
        jdbc:
          # see: https://vladmihalcea.com/how-to-store-date-time-and-timestamps-in-utc-time-zone-with-jdbc-and-hibernate/
          '[time_zone]': UTC
    # Disable Open Session In View
    open-in-view: false
  liquibase:
    # No Liquibase contexts
    contexts: none
  mvc:
    # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request
    throw-exception-if-no-handler-found: true
  resources:
    # Disable the static resource handling
    add-mappings: false
---
sgi:
  rest:
    api:
      eti-url: "http://sgi-eti-service:4280"    
      csp-url: "http://sgi-csp-service:4281"    
      usr-url: "http://sgi-usr-service:4282"    
      pii-url: "http://sgi-pii-service:4283"          
      rel-url: "http://sgi-rel-service:4284"          
      com-url: "http://sgi-com-service:4286"          
      rep-url: "http://sgi-rep-service:4287"          

spring:
  profiles: dev
  datasource:
    # Make sure database schema is created (schema.sql is executed)
    initialization-mode: always
    # We use a H2 in file database with PostgreSQL compatibility mode
    url: "jdbc:h2:./target/db/tp;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    # Enable Liquibase
    enabled: true
    # Default database schema
    default-schema: tp
    # Schema to use for Liquibase objects
    liquibase-schema: tp
    # Set Liquibase contexts same as spring profiles
    contexts: dev
    # Set Liquibase changeLog parameters
    parameters:
      schemaPrefix: "tp."
  jpa:
    hibernate:
      # Make sure Hibernate will not use the entities to create, update or validate the database
      # validate | update | create | create-drop
      ddl-auto: none
    properties:
      hibernate:
        # We use a H2 database with PostgreSQL compatibility mode
        dialect: org.hibernate.dialect.H2Dialect
        # Set default Hibernate schema
        '[default_schema]': tp
  security:
    oauth2:
      resourceserver:
        jwt:
          # JSON Web Key endpoint (with the cryptographic key to validate JSON Web Signature)
          jwk-set-uri: http://sgi-auth:8080/auth/realms/sgi/protocol/openid-connect/certs
          user-name-claim: user_ref_id
      client:
        registration:
          # "sgi" is the id used inside the redirect-uri-template, must be the same as your realm
          sgi:
            authorization-grant-type: authorization_code
            provider: keycloak
            scope: "openid,profile"
            client-name: SGI (user login)
            client-id: front
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          tp-service:
            authorization-grant-type: client_credentials
            provider: keycloak
            scope: sgi-eti
            client-name: SGI (service login)
            client-id: tp-service
            client-secret: a397c654-5899-469d-8ab4-ccbb4898a104
        provider:
          keycloak:
            issuer-uri: http://sgi-auth:8080/auth/realms/sgi
            user-name-attribute: user_ref_id
            token-uri: http://sgi-auth:8080/auth/realms/sgi/protocol/openid-connect/token
      # Enable login page if JWT not provided (enable only for development)
      #enable-login: true
    # Disable CSRF (disable only for development)
    #csrf:
      #enable: false
    # Disable X-Frame-Options (disable only for development)
    #frameoptions:
      #enable: false
  # H2 console
  h2:
    console:
      enabled: false
      #path: /h2-console
      #settings:
        #web-allow-others: true

logging:
  level:
    org:
      hibernate:
        # Log the SQL statements
        SQL: DEBUG
        type:
          descriptor:
            sql:
              # Log SQL query parameter binding
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            # Log JdbcTemplate Queries
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
---
sgi:
  rest:
    api:
      eti-url: "http://sgi-eti-service:8080"
      csp-url: "http://sgi-csp-service:8080"
      usr-url: "http://sgi-eti-service:8080"
      pii-url: "http://sgi-pii-service:8080"
      rel-url: "http://sgi-rel-service:8080"
      com-url: "http://sgi-com-service:8080"
      rep-url: "http://sgi-rep-service:8080"

spring:
  profiles: prod
  datasource:
    # Make sure database schema is created (schema.sql is executed)
    initialization-mode: always
    # We use PostgreSQL database
    url: "jdbc:postgresql://postgres:5432/tp"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  liquibase:
    # Enable Liquibase
    enabled: true
    # Default database schema
    default-schema: tp
    # Schema to use for Liquibase objects
    liquibase-schema: tp
    # Set Liquibase changeLog parameters
    parameters:
      schemaPrefix: "tp."
  jpa:
    hibernate:
      # Hibernate will use the entities to validate the database
      # validate | update | create | create-drop
      ddl-auto: none
    properties:
      hibernate:
        # We use a PostgreSQL database
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        # Set default Hibernate Schema
        '[default_schema]': tp
  security:
    oauth2:
      resourceserver:
        jwt:
          # JSON Web Key endpoint (with the cryptographic key to validate JSON Web Signature)
          jwk-set-uri: http://sgi-auth:8080/auth/realms/sgi/protocol/openid-connect/certs
          user-name-claim: user_ref_id
      client:
        registration:
          # "sgi" is the id used inside the redirect-uri-template, must be the same as your realm
          sgi:
            authorization-grant-type: authorization_code
            provider: keycloak
            scope: "openid,profile"
            client-name: SGI (user login)
            client-id: front
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          tp-service:
            authorization-grant-type: client_credentials
            provider: keycloak
            scope: sgi-eti
            client-name: SGI (service login)
            client-id: tp-service
            client-secret: a397c654-5899-469d-8ab4-ccbb4898a104
        provider:
          keycloak:
            issuer-uri: http://sgi-auth:8080/auth/realms/sgi
            user-name-attribute: user_ref_id
            token-uri: http://sgi-auth:8080/auth/realms/sgi/protocol/openid-connect/token
