
export interface ISolicitudProyectoSge {
  id: string;
  proyectoSgeRef: string;
  estado: Estado;
}

export enum Estado {
  ALTA_SOLICITUD_SGI = 'ALTA_SOLICITUD_SGI',
  ALTA_ACEPTADA_SGE = 'ALTA_ACEPTADA_SGE',
  ALTA_CONFIRMADA_SGI = 'ALTA_CONFIRMADA_SGI',
  ALTA_ERROR_SGI = 'ALTA_ERROR_SGI',
  ALTA_RECHAZADA_SGE = 'ALTA_RECHAZADA_SGE',
  ALTA_RECHAZO_CONFIRMADO_SGI = 'ALTA_RECHAZO_CONFIRMADO_SGI',
  MODIFICACION_SOLICITUD_SGI = 'MODIFICACION_SOLICITUD_SGI',
  MODIFICACION_ACEPTADA_SGE = 'MODIFICACION_ACEPTADA_SGE',
  MODIFICACION_RECHAZADA_SGE = 'MODIFICACION_RECHAZADA_SGE',
  MODIFICACION_CONFIRMADA_SGI = 'MODIFICACION_CONFIRMADA_SGI',
  MODIFICACION_RECHAZO_CONFIRMADO_SGI = 'MODIFICACION_RECHAZO_CONFIRMADO_SGI',
  REASIGNACION_ACEPTADA_SGE = 'REASIGNACION_ACEPTADA_SGE',
  REASIGNACION_CONFIRMADA_SGI = 'REASIGNACION_CONFIRMADA_SGI',
  REASIGNACION_ERROR_SGI = 'REASIGNACION_ERROR_SGI'
}
