export const EJECUCION_ECONOMICA_ROUTE_NAMES = {
  PROYECTOS: 'proyectos',
  EJECUCION_PRESUPUESTARIA_ESTADO_ACTUAL: 'ejecucion-presupuestaria-estado-actual',
  EJECUCION_PRESUPUESTARIA_GASTOS: 'ejecucion-presupuestaria-gastos',
  EJECUCION_PRESUPUESTARIA_INGRESOS: 'ejecucion-presupuestaria-ingresos',
  DETALLE_OPERACIONES_GASTOS: 'detalle-operaciones-gastos',
  DETALLE_OPERACIONES_INGRESOS: 'detalle-operaciones-ingresos',
  DETALLE_OPERACIONES_MODIFICACIONES: 'detalle-operaciones-modificaciones',
  FACTURAS_GASTOS: 'facturas-gastos',
  VIAJES_DIETAS: 'viajes-dietas',
  PERSONAL_CONTRATADO: 'personal-contratado',
  CLASIFICACION_GASTOS: 'clasificacion-gastos',
  VALIDACION_GASTOS: 'validacion-gastos',
  FACTURAS_EMITIDAS: 'facturas-emitidas',
  SEGUIMIENTO_JUSTIFICACION_RESUMEN: 'seguimiento-justificacion-resumen',
  SEGUIMIENTO_JUSTIFICACION_REQUERIMIENTOS: 'seguimiento-justificacion-requerimientos',
};
