INSERT INTO test.config 
(name, created_by, creation_date, last_modified_by, last_modified_date, description, value)
VALUES
('entidad-implantacion', NULL, NULL, NULL, NULL, 'Nombre de la entidad donde está instalada la aplicación', 'Universidad'),
('csp-conv-hitos-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Convocatoria Hito - OTRI', '["convocatoria.hitos.otri@sgi.es"]'),
('csp-conv-hitos-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Convocatoria Hito - OPE', '["convocatoria.hitos.ope@sgi.es"]'),
('csp-conv-hitos-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Convocatoria Hito - UGI', '["convocatoria.hitos.ugi@sgi.es"]'),
('csp-com-inicio-presentacion-gasto-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de inicio de presentacion de justificacion de gastos - OTRI', '["sample@sample.es"]'),
('csp-com-inicio-presentacion-gasto-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de inicio de presentacion de justificacion de gastos - OPE', '["sample@sample.es"]'),
('csp-com-inicio-presentacion-gasto-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de inicio de presentacion de justificacion de gastos - UGI', '["sample@sample.es"]'),
('csp-com-inicio-pres-seg-cientifico-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de inicio de presentacion del seguimiento científico - OTRI', '["sample@sample.es"]'),
('csp-com-inicio-pres-seg-cientifico-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de inicio de presentacion del seguimiento científico - OPE', '["sample@sample.es"]'),
('csp-com-inicio-pres-seg-cientifico-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de inicio de presentacion del seguimiento científico - UGI', '["sample@sample.es"]'),
('csp-sol-hitos-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Solicitudes Hito - OTRI', '["solicitud.hitos.otri@sgi.es"]'),
('csp-sol-hitos-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Solicitudes Hito - OPE', '["solicitud.hitos.ope@sgi.es"]'),
('csp-sol-hitos-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Solicitudes Hito - UGI', '["solicitud.hitos.ugi@sgi.es"]'),
('csp-com-sol-camb-est-solicitada-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de cambio de estado de solicitud a solicitada - OTRI', '["sample@sample.es"]'),
('csp-com-sol-camb-est-solicitada-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de cambio de estado de solicitud a solicitada - OPE', '["operum@um.es","msojo@um.es","javr@um.es","lcs@um.es"]'),
('csp-com-sol-camb-est-solicitada-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de cambio de estado de solicitud a solicitada - UGI', '["ugiproy@um.es","ugirrhh@um.es"]'),
('csp-com-sol-camb-est-alegaciones-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de cambio de estado de solicitud a alegaciones - OTRI', '["sample@sample.es"]'),
('csp-com-sol-camb-est-alegaciones-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de cambio de estado de solicitud a alegaciones - OPE', '["operum@um.es","msojo@um.es","javr@um.es","lcs@um.es"]'),
('csp-com-sol-camb-est-alegaciones-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios de comunicado de cambio de estado de solicitud a alegaciones - UGI', '["ugiproy@um.es","ugirrhh@um.es"]'),
('csp-vencim-periodo-pago-socio-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Vencimiento Periodo Pago Socio - OTRI', '["venc.periodo.pago.socio.otri@sgi.es"]'),
('csp-vencim-periodo-pago-socio-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Vencimiento Periodo Pago Socio - OPE', '["venc.periodo.pago.socio.ope@sgi.es"]'),
('csp-vencim-periodo-pago-socio-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Vencimiento Periodo Pago Socio - UGI', '["venc.periodo.pago.socio.ugi@sgi.es"]'),
('csp-inicio-fin-periodo-just-socio-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Inicio/Fin Periodo Justificación Socio - UG', '["aviso.just.periodo.socio.ugi@sgi.es"]'),
('csp-inicio-fin-periodo-just-socio-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Inicio/Fin Periodo Justificación Socio - UG', '["aviso.just.periodo.socio.ugi@sgi.es"]'),
('csp-inicio-fin-periodo-just-socio-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Inicio/Fin Periodo Justificación Socio - UG', '["aviso.just.periodo.socio.ugi@sgi.es"]'),
('csp-com-cal-fact-validarip-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatario de comunicados al validar una factura - OTRI', '["lmsi@um.es"]'),
('csp-com-cal-fact-validarip-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatario de comunicados al validar una factura - OPE', '["operum@um.es","msojo@um.es","javr@um.es","lcs@um.es"]'),
('csp-com-cal-fact-validarip-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatario de comunicados al validar una factura - UGI', '["ugiproy@um.es","ugirrhh@um.es"]'),
('id-entidad-sgemp', NULL, NULL, NULL, NULL, 'Identificador de la entidad donde esta instalada la aplicación en el sistema de gestión de empresas', 'Q3018001'),
('pii-com-fecha-fin-pri-sol-prot-destinatarios', NULL, NULL, NULL, NULL, 'Destinatarios defecto PII COM Fin Fecha Prioridad Solicitud Protección OTRI', '["venc.periodo.pago.socio.otri@sgi.es"]'),
('fin-plaz-fases-nac-reg-sol-prot-destinatarios', NULL, NULL, NULL, NULL, 'Destinatarios defecto PII COM Aviso fin de plazo de entrada en fases nacionales/regionales de una Solicitud Protección OTRI', '["venc.periodo.pago.socio.otri@sgi.es"]'),
('prc-proceso-baremacion-destinatarios', NULL, NULL, NULL, NULL, 'Destinatarios proceso baremacion PRC', '["proceso.baremacion.prc@sgi.es"]'),
('csp-pro-hitos-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Solicitudes Hito - OTRI', '["proyecto.hitos.otri@sgi.es"]'),
('csp-pro-hitos-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Solicitudes Hito - OPE', '["proyecto.hitos.ope@sgi.es"]'),
('csp-pro-hitos-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Solicitudes Hito - UGI', '["proyecto.hitos.ugi@sgi.es"]'),
('csp-pro-ex-mod-aut-participacion-destinatarios', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Modificar Autorización del estado de participación de un proyecto externo', '["pro.ext.mod.aut1@sgi.es", "pro.ext.mod.aut2@sgi.es"]'),
('csp-pro-recep-not-cvn-pext-destinatarios', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Recepción Notificación CVN proyecto externo', '["pro.ext.recep.not.cvn.aut1@sgi.es", "pro.ext.recep.not-cvn.aut2@sgi.es"]'),
('pii-fecha-limite-procedimiento-destinatarios', NULL, NULL, NULL, NULL, 'Destinatarios defecto PII Fecha límite de procedimiento', '["fecha.limite.proce01@sgi.es", "fecha.limite.proce02@sgi.es"]'),
('eti-blockchain-enable', NULL, NULL, NULL, NULL, 'Indica si se va a realizar la integración con el blockchain en el módulo de ética', 'false'),
('csp-conv-fases-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Convocatoria Fases - OTRI', '["convocatoria.fases.otri@sgi.es"]'),
('csp-conv-fases-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Convocatoria Fases - OPE', '["convocatoria.fases.ope@sgi.es"]'),
('csp-conv-fases-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Convocatoria Fases - UGI', '["convocatoria.fases.ugi@sgi.es"]'),
('csp-pro-fases-destinatarios-1', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Proyecto Fases - OTRI', '["proyecto.fases.otri@sgi.es"]'),
('csp-pro-fases-destinatarios-2', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Proyecto Fases - OPE', '["proyecto.fases.ope@sgi.es"]'),
('csp-pro-fases-destinatarios-3', NULL, NULL, NULL, NULL, 'Destinatarios defecto CSP Proyecto Fases - UGI', '["proyecto.fases.ugi@sgi.es"]'),
('nombre-sistema-gestion-externo', NULL, NULL, NULL, NULL, 'Nombre de la opción del menú que hará ir a la url del sistema gestion externo.', 'Acceso Goliat Hércules'),
('url-sistema-gestion-externo', NULL, NULL, NULL, NULL, 'URL sistema gestion externo', 'https://goliathtest.um.es');
