import { marker } from '@biesbjerg/ngx-translate-extract-marker';

export enum ESTADO_MEMORIA {
  EN_ELABORACION = 1,
  COMPLETADA = 2,
  EN_SECRETARIA = 3,
  EN_SECRETARIA_REVISION_MINIMA = 4,
  EN_EVALUACION = 5,
  FAVORABLE_PENDIENTE_MODIFICACIONES_MINIMAS = 6,
  PENDIENTE_CORRECCIONES = 7,
  NO_PROCEDE_EVALUAR = 8,
  FIN_EVALUACION = 9,
  ARCHIVADA = 10,
  COMPLETADA_SEGUIMIENTO_ANUAL = 11,
  EN_SECRETARIA_SEGUIMIENTO_ANUAL = 12,
  EN_EVALUACION_SEGUIMIENTO_ANUAL = 13,
  FIN_EVALUACION_SEGUIMIENTO_ANUAL = 14,
  SOLICITUD_MODIFICACION = 15,
  COMPLETADA_SEGUIMIENTO_FINAL = 16,
  EN_SECRETARIA_SEGUIMIENTO_FINAL = 17,
  EN_SECRETARIA_SEGUIMIENTO_FINAL_ACLARACIONES = 18,
  EN_EVALUACION_SEGUIMIENTO_FINAL = 19,
  FIN_EVALUACION_SEGUIMIENTO_FINAL = 20,
  EN_ACLARACION_SEGUIMIENTO_FINAL = 21,
  SUBSANACION = 22,
  DESFAVORABLE = 23,
  SOLICITUD_MODIFICACION_SEGUIMIENTO_ANUAL = 24,
  EN_SECRETARIA_SEGUIMIENTO_ANUAL_MODIFICACION = 25
}

export const ESTADO_MEMORIA_MAP: Map<ESTADO_MEMORIA, string> = new Map([
  [ESTADO_MEMORIA.EN_ELABORACION, marker(`eti.estado-memoria.EN_ELABORACION`)],
  [ESTADO_MEMORIA.COMPLETADA, marker(`eti.estado-memoria.COMPLETADA`)],
  [ESTADO_MEMORIA.EN_SECRETARIA, marker(`eti.estado-memoria.EN_SECRETARIA`)],
  [ESTADO_MEMORIA.EN_SECRETARIA_REVISION_MINIMA, marker(`eti.estado-memoria.EN_SECRETARIA_REVISION_MINIMA`)],
  [ESTADO_MEMORIA.EN_EVALUACION, marker(`eti.estado-memoria.EN_EVALUACION`)],
  [ESTADO_MEMORIA.FAVORABLE_PENDIENTE_MODIFICACIONES_MINIMAS, marker(`eti.estado-memoria.FAVORABLE_PENDIENTE_MODIFICACIONES_MINIMAS`)],
  [ESTADO_MEMORIA.PENDIENTE_CORRECCIONES, marker(`eti.estado-memoria.PENDIENTE_CORRECCIONES`)],
  [ESTADO_MEMORIA.NO_PROCEDE_EVALUAR, marker(`eti.estado-memoria.NO_PROCEDE_EVALUAR`)],
  [ESTADO_MEMORIA.FIN_EVALUACION, marker(`eti.estado-memoria.FIN_EVALUACION`)],
  [ESTADO_MEMORIA.ARCHIVADA, marker(`eti.estado-memoria.ARCHIVADA`)],
  [ESTADO_MEMORIA.COMPLETADA_SEGUIMIENTO_ANUAL, marker(`eti.estado-memoria.COMPLETADA_SEGUIMIENTO_ANUAL`)],
  [ESTADO_MEMORIA.EN_SECRETARIA_SEGUIMIENTO_ANUAL, marker(`eti.estado-memoria.EN_SECRETARIA_SEGUIMIENTO_ANUAL`)],
  [ESTADO_MEMORIA.EN_EVALUACION_SEGUIMIENTO_ANUAL, marker(`eti.estado-memoria.EN_EVALUACION_SEGUIMIENTO_ANUAL`)],
  [ESTADO_MEMORIA.FIN_EVALUACION_SEGUIMIENTO_ANUAL, marker(`eti.estado-memoria.FIN_EVALUACION_SEGUIMIENTO_ANUAL`)],
  [ESTADO_MEMORIA.SOLICITUD_MODIFICACION, marker(`eti.estado-memoria.SOLICITUD_MODIFICACION`)],
  [ESTADO_MEMORIA.COMPLETADA_SEGUIMIENTO_FINAL, marker(`eti.estado-memoria.COMPLETADA_SEGUIMIENTO_FINAL`)],
  [ESTADO_MEMORIA.EN_SECRETARIA_SEGUIMIENTO_FINAL, marker(`eti.estado-memoria.EN_SECRETARIA_SEGUIMIENTO_FINAL`)],
  [ESTADO_MEMORIA.EN_SECRETARIA_SEGUIMIENTO_FINAL_ACLARACIONES, marker(`eti.estado-memoria.EN_SECRETARIA_SEGUIMIENTO_FINAL_ACLARACIONES`)],
  [ESTADO_MEMORIA.EN_EVALUACION_SEGUIMIENTO_FINAL, marker(`eti.estado-memoria.EN_EVALUACION_SEGUIMIENTO_FINAL`)],
  [ESTADO_MEMORIA.FIN_EVALUACION_SEGUIMIENTO_FINAL, marker(`eti.estado-memoria.FIN_EVALUACION_SEGUIMIENTO_FINAL`)],
  [ESTADO_MEMORIA.EN_ACLARACION_SEGUIMIENTO_FINAL, marker(`eti.estado-memoria.EN_ACLARACION_SEGUIMIENTO_FINAL`)],
  [ESTADO_MEMORIA.SUBSANACION, marker(`eti.estado-memoria.SUBSANACION`)],
  [ESTADO_MEMORIA.DESFAVORABLE, marker(`eti.estado-memoria.DESFAVORABLE`)],
  [ESTADO_MEMORIA.SOLICITUD_MODIFICACION_SEGUIMIENTO_ANUAL, marker(`eti.estado-memoria.SOLICITUD_MODIFICACION_SEGUIMIENTO_ANUAL`)],
  [ESTADO_MEMORIA.EN_SECRETARIA_SEGUIMIENTO_ANUAL_MODIFICACION, marker(`eti.estado-memoria.EN_SECRETARIA_SEGUIMIENTO_ANUAL_MODIFICACION`)]
]);

export class TipoEstadoMemoria {

  /** ID */
  id: number;
  /** Nombre */
  nombre: string;
  /** Activo */
  activo: boolean;

  constructor() {
    this.id = null;
    this.nombre = null;
    this.activo = true;
  }

}
