
export enum ESTADO_MEMORIA {
  EN_ELABORACION = 1,
  COMPLETADA = 2,
  EN_SECRETARIA = 3,
  EN_SECRETARIA_REVISION_MINIMA = 4,
  EN_EVALUACION = 5,
  FAVORABLE_PENDIENTE_MODIFICACIONES_MINIMAS = 6,
  PENDIENTE_CORRECCIONES = 7,
  NO_PROCEDE_EVALUAR = 8,
  FIN_EVALUACION = 9,
  ARCHIVADA = 10,
  COMPLETADA_SEGUIMIENTO_ANUAL = 11,
  EN_SECRETARIA_SEGUIMIENTO_ANUAL = 12,
  EN_EVALUACION_SEGUIMIENTO_ANUAL = 13,
  FIN_EVALUACION_SEGUIMIENTO_ANUAL = 14,
  SOLICITUD_MODIFICACION = 15,
  COMPLETADA_SEGUIMIENTO_FINAL = 16,
  EN_SECRETARIA_SEGUIMIENTO_FINAL = 17,
  EN_SECRETARIA_SEGUIMIENTO_FINAL_ACLARACIONES = 18,
  EN_EVALUACION_SEGUIMIENTO_FINAL = 19,
  FIN_EVALUACION_SEGUIMIENTO_FINAL = 20,
  EN_ACLARACION_SEGUIMIENTO_FINAL = 21
}

export class TipoEstadoMemoria {

  /** ID */
  id: number;
  /** Nombre */
  nombre: string;
  /** Activo */
  activo: boolean;

  constructor() {
    this.id = null;
    this.nombre = null;
    this.activo = true;
  }

}
