export const CSP_ROUTE_NAMES = {
  CONVOCATORIA: 'convocatoria',
  SOLICITUD: 'solicitud',
  FUENTE_FINANCIACION: 'fuente-financiacion',
  TIPO_DOCUMENTO: 'tipo-documentos',
  TIPO_FINALIDAD: 'tipo-finalidades',
  TIPO_ENLACE: 'tipo-enlaces',
  TIPO_HITO: 'tipo-hitos',
  TIPO_FASE: 'tipo-fases',
  MODELO_EJECUCION: 'modelo-ejecuciones',
  PLANES_INVESTIGACION: 'planes-investigacion',
  CONCEPTO_GASTO: 'concepto-gasto',
  TIPO_FINANCIACION: 'tipo-financiaciones',
  AREA_TEMATICA: 'area-tematica',
  PROYECTO: 'proyectos',
  EJECUCION_ECONOMICA: 'ejecucion-economica',
  NOTIFICACION_PRESUPUESTO_SGE: 'notificacion-presupuesto-sge',
  AUTORIZACION: 'autorizaciones',
  NOTIFICACION_CVN: 'notificaciones-cnv'
};
