import { DateTime } from 'luxon';
import { CVN_TIPO_PRODUCCION } from 'src/app/module/prc/shared/cvn/literales-cvn';
import { IProduccionCientifica } from './produccion-cientifica';

export interface IPublicacion extends IProduccionCientifica {
  tituloPublicacion: string;
  tipoProduccion: TipoProduccion;
  fechaPublicacion: DateTime;
}

export enum TipoProduccion {
  CAPITULO_LIBRO = '004',
  INFORME_CIENTIFICO = '018',
  ARTICULO_CIENTIFICO = '020',
  LIBRO_CIENTIFICO = '032',
  ARTICULOS_PRENSA = '075',
  DICCIONARIO_COMUN = '106',
  REVISTAS_DIFUSION_GENERAL = '173',
  ARTICULO_ENCICLOPEDIA = '202',
  ARTICULO_DIVULGACION = '203',
  TRADUCCION = '204',
  RESENA = '205',
  REVISION_BIBLIOGRAFICA = '206',
  LIBRO_DIVULGACION = '207',
  EDICION_CIENTIFICA = '208',
  DICCIONARIO_CIENTIFICO = '209',
  OTROS = 'OTHERS',
  COMENTARIO_SISTEMATICO_NORMAS = 'COMENTARIO_SISTEMATICO_NORMAS'
}

export const TIPO_PRODUCCION_MAP: Map<TipoProduccion, string> = new Map([
  [TipoProduccion.CAPITULO_LIBRO, CVN_TIPO_PRODUCCION.CAPITULO_LIBRO],
  [TipoProduccion.INFORME_CIENTIFICO, CVN_TIPO_PRODUCCION.INFORME_CIENTIFICO],
  [TipoProduccion.ARTICULO_CIENTIFICO, CVN_TIPO_PRODUCCION.ARTICULO_CIENTIFICO],
  [TipoProduccion.LIBRO_CIENTIFICO, CVN_TIPO_PRODUCCION.LIBRO_CIENTIFICO],
  [TipoProduccion.ARTICULOS_PRENSA, CVN_TIPO_PRODUCCION.ARTICULOS_PRENSA],
  [TipoProduccion.DICCIONARIO_COMUN, CVN_TIPO_PRODUCCION.DICCIONARIO_COMUN],
  [TipoProduccion.REVISTAS_DIFUSION_GENERAL, CVN_TIPO_PRODUCCION.REVISTAS_DIFUSION_GENERAL],
  [TipoProduccion.ARTICULO_ENCICLOPEDIA, CVN_TIPO_PRODUCCION.ARTICULO_ENCICLOPEDIA],
  [TipoProduccion.ARTICULO_DIVULGACION, CVN_TIPO_PRODUCCION.ARTICULO_DIVULGACION],
  [TipoProduccion.TRADUCCION, CVN_TIPO_PRODUCCION.TRADUCCION],
  [TipoProduccion.RESENA, CVN_TIPO_PRODUCCION.RESENA],
  [TipoProduccion.REVISION_BIBLIOGRAFICA, CVN_TIPO_PRODUCCION.REVISION_BIBLIOGRAFICA],
  [TipoProduccion.LIBRO_DIVULGACION, CVN_TIPO_PRODUCCION.LIBRO_DIVULGACION],
  [TipoProduccion.EDICION_CIENTIFICA, CVN_TIPO_PRODUCCION.EDICION_CIENTIFICA],
  [TipoProduccion.DICCIONARIO_CIENTIFICO, CVN_TIPO_PRODUCCION.DICCIONARIO_CIENTIFICO],
  [TipoProduccion.OTROS, CVN_TIPO_PRODUCCION.OTROS],
  [TipoProduccion.COMENTARIO_SISTEMATICO_NORMAS, CVN_TIPO_PRODUCCION.COMENTARIO_SISTEMATICO_NORMAS]
]);
