-- vacia la bd
DELETE FROM test.respuesta
DELETE FROM test.documentacion_memoria
DELETE FROM test.tarea
DELETE FROM test.informe
DELETE FROM test.estado_memoria
DELETE FROM test.comentario
DELETE FROM test.evaluacion
DELETE FROM test.memoria
DELETE FROM test.tipo_memoria_comite
DELETE FROM test.asistentes
DELETE FROM test.conflicto_interes
DELETE FROM test.evaluador
DELETE FROM test.equipo_trabajo
DELETE FROM test.peticion_evaluacion
DELETE FROM test.tipo_actividad
DELETE FROM test.tipo_investigacion_tutelada
DELETE FROM test.tipo_memoria
DELETE FROM test.tipo_documento
DELETE FROM test.estado_acta
DELETE FROM test.acta
DELETE FROM test.tipo_estado_acta
DELETE FROM test.convocatoria_reunion
DELETE FROM test.tipo_convocatoria_reunion
DELETE FROM test.apartado
DELETE FROM test.bloque
DELETE FROM test.comite
DELETE FROM test.tipo_estado_memoria
DELETE FROM test.formacion_especifica
DELETE FROM test.cargo_comite
DELETE FROM test.dictamen
DELETE FROM test.tipo_comentario
DELETE FROM test.formulario
DELETE FROM test.configuracion
DELETE FROM test.tipo_evaluacion
DELETE FROM test.retrospectiva
DELETE FROM test.estado_retrospectiva
DELETE FROM test.tipo_tarea
DELETE FROM test.checklist
DELETE FROM test.formly